
# this is the puls, the monitor and the static app.
app:
  # image: daneroo/im-rain
  # image: imetrical/im-rain
  build: .
  # environment:
  #   - COUCH_HOST=couch
  #   - NODE_NAME
  links:
    - mydb
    - red
    - rabbit
  ports:
    - 80:8000
  restart: unless-stopped

grafana:
  image: grafana/grafana:2.6.0
  volumes:
    - ./data/grafana/grafana.db:/var/lib/grafana/grafana.db
  links:
    - prom
  ports:
    - 3000:3000
  restart: unless-stopped

prom:
  # build: docker/prometheus
  image: prom/prometheus:0.18.0
  volumes:
    - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  links:
    - app
    - redisexporter
  ports:
    - 9090:9090
  restart: unless-stopped

red:
  image: redis
  ports:
    - 6379:6379
  restart: unless-stopped

redisexporter:
  image: 21zoo/redis_exporter
  # actually just command params because there is an entrypoint
  command: --redis.addr=red:6379
  links:
    - red
  ports:
    - 9121:9121
  restart: unless-stopped

rabbit:
  image: rabbitmq:management
  ports:
    - 5672:5672
    - 15672:15672 # web management interface
  restart: unless-stopped

mydb:
  image: mysql:5.7
  environment:
    # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_ROOT_PASSWORD=supersecret
    - MYSQL_DATABASE=queue
    - MYSQL_USER=imetrical
    - MYSQL_PASSWORD=secret
  ports:
    - 3306:3306
  restart: unless-stopped
