
# this is the puls, the monitor and the static app.
app:
  # image: daneroo/im-rain
  # image: imetrical/im-rain
  build: .
  # environment:
  #   - COUCH_HOST=couch
  #   - NODE_NAME
  links:
    - mydb
    - red
    - rabbit
  ports:
    - 80:8000

prom:
  build: docker/prometheus
  links:
    - app
    - redisexporter
  ports:
    - 9090:9090

red:
  image: redis
  ports:
    - 6379:6379

redisexporter:
  image: 21zoo/redis_exporter
  # actually just command params because there is an entrypoint
  command: --redis.addr=red:6379
  links:
    - red
  ports:
    - 9121:9121

rabbit:
  image: rabbitmq:management
  ports:
    - 5672:5672
    - 15672:15672 # web management interface

mydb:
  image: mysql
  environment:
    # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_ROOT_PASSWORD=supersecret
    - MYSQL_DATABASE=queue
    - MYSQL_USER=imetrical
    - MYSQL_PASSWORD=secret
  ports:
    - 3306:3306
